### Get all products
GET http://localhost:8000/products

###

### Get one product
GET http://localhost:8000/products/1

###

### Create product
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "T-Shirt Green",
    "price": 2000,
    "quantity": 50
}

### Update product
PUT http://localhost:8000/products/2
Content-Type: application/json

{
    "name": "iPhone",
    "price": 120000,
    "quantity": 50
}

### Delete product
DELETE http://localhost:8000/products/5
